# Symbols kept tiny for MVP; extend anytime
equities:
  - VOO
  - QQQ
bonds:
  - TLT
crypto:
  - BTC-USD

macro:
  # FRED series IDs
  - CPIAUCSL      # CPI (Index)
  - T10Y3M        # 10Y minus 3M spread

# Daily bars since 2018 for a quick first backtest later
start_date: "2018-01-01"
interval: "1d"

# Output
data_dir: "data"
assets_parquet: "data/assets.parquet"
macro_parquet: "data/macro.parquet"
merged_parquet: "data/merged.parquet"
risk_parquet: "data/risk.parquet"


# --- RISK PARAMS (MVP) ---
risk:
  ret_col: "ret"
  vol_window: 20
  var_window: 60
  cvar_alpha: 0.05
  liq_window: 20

optimizer:
  lookback: 252      # trading days used to estimate μ, Σ
  gamma: 2.5         # risk aversion (mean-variance utility)
  tau: 0.05          # BL uncertainty scalar on prior
  long_only: true
  market_weights: equal   # MVP: equal weights as market proxy

  # Optional views (MVP example): BTC expected to beat TLT by 5% annualized
  views:
    - type: relative
      long: "BTC-USD"
      short: "TLT"
      annualized_delta: 0.05   # +5%/year
      uncertainty: 0.10        # 10%/year std belief


