# Symbols kept tiny for MVP; extend anytime
equities:
  - VOO
  - QQQ
bonds:
  - TLT
crypto:
  - BTC-USD

macro:
  # FRED series IDs
  - CPIAUCSL      # CPI (Index)
  - T10Y3M        # 10Y minus 3M spread

# Daily bars since 2018 for a quick first backtest later
start_date: "2018-01-01"
interval: "1d"

# Output
data_dir: "data"
assets_parquet: "data/assets.parquet"
macro_parquet: "data/macro.parquet"
merged_parquet: "data/merged.parquet"
risk_parquet: "data/risk.parquet"


# --- RISK PARAMS (MVP) ---
risk:
  ret_col: "ret"
  vol_window: 20
  var_window: 60
  cvar_alpha: 0.05
  liq_window: 20


optimizer:
  lookback: 252
  gamma: 2.5
  tau: 0.05
  shrinkage: 0.10         # keep modest; tune 0.05–0.15
  enable_equal_weight_fallback: true
  long_only: true
  market_weights: equal


# --- Backtest (MVP) ---
backtest:
  rebalance: "M"        # monthly
  initial_capital: 500000
  tc_bps: 5             # transaction cost in basis points (0.05%) per 1x turnover
  benchmark: "SPY"      # S&P 500 proxy
  lookback: 252         # lookback used by optimizer at each rebalance

# Outputs
backtest_parquet: "data/backtest_results.parquet"
perf_plot_path: "data/perf_equity_vs_benchmark.png"
dd_plot_path: "data/rolling_drawdown.png"



